export const SET_CLASSNOW = 'SET_CLASSNOW';
export const IS_SIGNIN = 'IS_SIGNIN';
export const SET_DATA = 'SET_DATA';
export const ON_FIRST_REGISTER_CLASS = 'ON_FIRST_REGISTER_CLASS';
export const ON_MODAL_SAME_TRAVEL_TIME = 'ON_MODAL_SAME_TRAVEL_TIME';
export const SET_SHARED_TRAVEL_TIME = 'SET_SHARED_TRAVEL_TIME';
export const RE_RENDER_SAME_TRAVEL_TIME = 'RE_RENDER_SAME_TRAVEL_TIME';

export const ADD_STUDENTS_REQUEST = 'ADD_STUDENTS_REQUEST';
export const ADD_STUDENTS_SUCCESS = 'ADD_STUDENTS_SUCCESS';
export const ADD_STUDENTS_FAILURE = 'ADD_STUDENTS_FAILURE';

export const GET_ALL_STUDENTS_NAME_REQUEST = 'GET_ALL_STUDENTS_NAME_REQUEST';
export const GET_ALL_STUDENTS_NAME_SUCCESS = 'GET_ALL_STUDENTS_NAME_SUCCESS';
export const GET_ALL_STUDENTS_NAME_FAILURE = 'GET_ALL_STUDENTS_NAME_FAILURE';

export const SET_STUDENT_FROM_MY_STUDENT = 'SET_STUDENT_FROM_MY_STUDENT';

export const ON_MODAL_CHOOSE_A_STUDENT_IN_MY_STUDENT = 'ON_MODAL_CHOOSE_A_STUDENT_IN_MY_STUDENT';

export const ON_CONFIRM_CHOOSE_STUDENT_FROM_MY_STUDENTS = 'ON_CONFIRM_CHOOSE_STUDENT_FROM_MY_STUDENTS';

export const ADD_CLASS_REQUEST = 'ADD_CLASS_REQUEST';
export const ADD_CLASS_SUCCESS = 'ADD_CLASS_SUCCESS';
export const ADD_CLASS_FAILURE = 'ADD_CLASS_FAILURE';

export const GET_USER_DATA_REQUEST = 'GET_USER_DATA_REQUEST';
export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';

export const ON_MODAL_ADD_HOMEWORK = 'ON_MODAL_ADD_HOMEWORK';

export const SAVE_A_HOMEWORK_REQUEST = 'SAVE_A_HOMEWORK_REQUEST';
export const SAVE_A_HOMEWORK_SUCCESS = 'SAVE_A_HOMEWORK_SUCCESS';
export const SAVE_A_HOMEWORK_FAILURE = 'SAVE_A_HOMEWORK_FAILURE';

export const UPDATE_NOTE_SCHEDULE_REQUEST = 'UPDATE_NOTE_SCHEDULE_REQUEST';
export const UPDATE_NOTE_SCHEDULE_SUCCESS = 'UPDATE_NOTE_SCHEDULE_SUCCESS';
export const UPDATE_NOTE_SCHEDULE_FAILURE = 'UPDATE_NOTE_SCHEDULE_FAILURE';

export const ON_MODAL_UPDATE_NEXT_LESSONS = 'ON_MODAL_UPDATE_NEXT_LESSONS';

export const UPDATE_SCHEDULE_NEXT_LESSONS_REQUEST = 'UPDATE_SCHEDULE_NEXT_LESSONS_REQUEST';
export const UPDATE_SCHEDULE_NEXT_LESSONS_SUCCESS = 'UPDATE_SCHEDULE_NEXT_LESSONS_SUCCESS';
export const UPDATE_SCHEDULE_NEXT_LESSONS_FAILURE = 'UPDATE_SCHEDULE_NEXT_LESSONS_FAILURE';

export const UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_REQUEST = 'UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_REQUEST';
export const UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_SUCCESS = 'UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_SUCCESS';
export const UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_FAILURE = 'UPDATE_SCHEDULE_NEXT_LESSONS_FOLLOW_TODAY_FAILURE';

export const ON_MODAL_NOTICE = 'ON_MODAL_NOTICE';

export const ON_DELETE_LESSONS = 'ON_DELETE_LESSONS';