export const SET_CLASSNOW = 'SET_CLASSNOW';
export const IS_SIGNIN = 'IS_SIGNIN';
export const SET_DATA = 'SET_DATA';
export const ON_FIRST_REGISTER_CLASS = 'ON_FIRST_REGISTER_CLASS';
export const ON_MODAL_SAME_TRAVEL_TIME = 'ON_MODAL_SAME_TRAVEL_TIME';
export const SET_SHARED_TRAVEL_TIME = 'SET_SHARED_TRAVEL_TIME';
export const RE_RENDER_SAME_TRAVEL_TIME = 'RE_RENDER_SAME_TRAVEL_TIME';

export const ADD_A_STUDENT_REQUEST = 'ADD_A_STUDENT_REQUEST';
export const ADD_A_STUDENT_SUCCESS = 'ADD_A_STUDENT_SUCCESS';
export const ADD_A_STUDENT_FAILURE = 'ADD_A_STUDENT_FAILURE';